services:

  Mooc.Courses.application.CourseCreator:
    class: ../../../../../Context/Mooc/Courses/application/CourseCreator
    arguments: ["@Mooc.Courses.application.CourseRepository"]
  
  Mooc.Courses.application.CourseRepository:
    class: ../../../../../Context/Mooc/Courses/infractructure/persistence/FileCourseRepository
    arguments: []